export const SET_EXPRESSION = 'SET_EXPRESSION';

export const CLEAR_EXPRESSION = 'CLEAR_EXPRESSION';

export const DELETE_LAST_EXPRESSION_ENTRY = 'DELETE_LAST_EXPRESSION_ENTRY';

export const EVALUATE_EXPRESSION = 'EVALUATE_EXPRESSION';

export const SQUARE = 'SQUARE';

export const SQUARE_ROOT = 'SQUARE_ROOT';